<a href="https://colab.research.google.com/github/daniyalmusman/SQL/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

In [11]:
%%sql

SELECT
  p.categoryname,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS "2022_revenue"
FROM product p
LEFT JOIN sales s
ON p.productkey = s.productkey
GROUP BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  2022_revenue
0                          Audio     766938.21
1                    Cell phones    8119665.07
2        Cameras and camcorders     2382532.56
3                   TV and Video    5815336.61
4                Home Appliances    6612446.68
5                 Games and Toys     316127.30
6  Music, Movies and Audio Books    2989297.28
7                      Computers   17862213.49

In [19]:
%%sql

SELECT
  DISTINCT EXTRACT (YEAR FROM s.orderdate) AS order_year,
  SUM(CASE WHEN p.categoryname = 'Audio' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS audio_revenue
  FROM product p
LEFT JOIN sales s
ON p.productkey = s.productkey
GROUP BY order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_year  audio_revenue
0       2021      393160.16
1       2022      766938.21
2       2020      368886.61
3       2024      209228.64
4       2016      335737.84
5       2015      170872.15
6       2019      930937.96
7       2017      478188.73
8       2018      970257.63
9       2023      688690.18