<a href="https://colab.research.google.com/github/daniyalmusman/SQL/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

In [ ]:
%%sql

SELECT
  p.categoryname,
  SUM(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS "2022_revenue"
FROM product p
LEFT JOIN sales s
ON p.productkey = s.productkey
GROUP BY p.categoryname

In [ ]:
%%sql

SELECT
  DISTINCT EXTRACT (YEAR FROM s.orderdate) AS order_year,
  SUM(CASE WHEN p.categoryname = 'Audio' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS audio_revenue
  FROM product p
LEFT JOIN sales s
ON p.productkey = s.productkey
GROUP BY order_year

In [ ]:
%%sql

SELECT
  DATE_TRUNC('month', orderdate) AS order_month,
  SUM(netprice * quantity * exchangerate)::BIGINT
FROM
  sales
GROUP BY
  order_month
ORDER BY
  order_month
LIMIT 10

In [ ]:
%%sql

SELECT
  DATE_TRUNC('month', orderdate) AS order_month,
  ROUND(SUM(netprice * quantity * exchangerate)::numeric, 2) AS net_revenue
FROM
  sales
GROUP BY
  DATE_TRUNC('month', orderdate)
ORDER BY
  order_month
LIMIT 10;

In [ ]:
%%sql

WITH c_year AS (SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) as cohort_year
FROM
  sales
)

SELECT
  cy.cohort_year,
  EXTRACT(YEAR FROM s.orderdate) as purchase_year,
  SUM(s.netprice * s.quantity * s.exchangerate) as yearly_purchase
FROM
  sales AS s
LEFT JOIN
  c_year AS cy
ON cy.customerkey = s.customerkey
GROUP BY
  purchase_year, cy.cohort_year
ORDER BY
  cy.cohort_year, purchase_year
LIMIT 50

In [25]:
%%sql

WITH cohort_window AS (
SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year,
  EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM
  sales)

SELECT
  COUNT(DISTINCT customerkey) AS customer_count,
  cohort_year,
  purchase_year
FROM
  cohort_window
GROUP BY
  cohort_year, purchase_year
ORDER BY
  cohort_year, purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

    customer_count cohort_year purchase_year
0             2825        2015          2015
1              126        2015          2016
2              149        2015          2017
3              348        2015          2018
4              388        2015          2019
5              171        2015          2020
6              295        2015          2021
7              600        2015          2022
8              499        2015          2023
9              146        2015          2024
10            3397        2016          2016
11             174        2016          2017
12             374        2016          2018
13             457        2016          2019
14             205        2016          2020
15             336        2016          2021
16             746        2016          2022
17             573        2016          2023
18             183        2016          2024
19            4068        2017          2017
20             473        2017          2018
21             570        2017          2019
22             251        2017          2020
23             450        2017          2021
24             943        2017          2022
25             738        2017          2023
26             246        2017          2024
27            7446        2018          2018
28            1081        2018          2019
29             475        2018          2020
30             779        2018          2021
31            1644        2018          2022
32            1407        2018          2023
33             426        2018          2024
34            7755        2019          2019
35             523        2019          2020
36             873        2019          2021
37            1700        2019          2022
38            1439        2019          2023
39             370        2019          2024
40            3031        2020          2020
41             358        2020          2021
42             694        2020          2022
43             547        2020          2023
44             163        2020          2024
45            4663        2021          2021
46            1051        2021          2022
47             889        2021          2023
48             268        2021          2024
49            9010        2022          2022
50            1764        2022          2023
51             561        2022          2024
52            5890        2023          2023
53             332        2023          2024
54            1402        2024          2024

In [27]:
%%sql

WITH cohort_window AS (
SELECT DISTINCT
  customerkey,
  EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year
FROM
  sales),

ltv_window AS (SELECT
  cw.customerkey,
  cw.cohort_year,
  SUM(quantity * netprice * exchangerate) AS customer_ltv
FROM
  cohort_window AS cw
LEFT JOIN
  sales AS s
ON cw.customerkey = s.customerkey
GROUP BY
  cw.customerkey,
  cw.cohort_year
  )

SELECT
  customerkey,
  cohort_year,
  customer_ltv,
  AVG(customer_ltv) OVER(PARTITION BY cohort_year) AS cohort_ltv
FROM
  ltv_window
ORDER BY cohort_year, customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  cohort_ltv
0             4376        2015        182.00     5271.59
1             4403        2015       9530.35     5271.59
2             4925        2015       6078.08     5271.59
3             5729        2015        192.16     5271.59
4             6048        2015       1903.89     5271.59
...            ...         ...           ...         ...
49482      2093965        2024        475.22     2037.55
49483      2095129        2024        156.00     2037.55
49484      2095691        2024        326.00     2037.55
49485      2096470        2024        535.78     2037.55
49486      2097541        2024       1143.15     2037.55

[49487 rows x 4 columns]